"""Main orchestrator: resolve topic → determine fields → extract values.

Links together the three extraction layers:

1. ``core.eml_parser``  — load and normalise the EML input.
2. ``core.templates``  — manual field registry: pre-defined topic → field
   mappings for known domains (primary path).
3. ``core.dynamic_schema`` — dynamic field discovery for unrecognised
   topics (fallback): derives fields from key-value pairs, noun phrases,
   and semantic similarity.
4. ``core.gliner_extractor`` — zero-shot extraction with a regex-based
   fallback for missing labels.

Public class:

    >>> from core.engine import TopicEmailExtractor
    >>> ext = TopicEmailExtractor()
    >>> result = ext.extract(eml_source="sample.eml", topic="job application")
    >>> print(result.extracted_data)
"""
from __future__ import annotations

import json
import logging
from dataclasses import dataclass, field, asdict
from typing import Optional

from .eml_parser import (
    parse_eml, ParsedEmail, extract_sender,
    detect_forwarded, extract_forwarded_sender,
    strip_forward_envelope, strip_quoted_reply, strip_trailing_signature,
)
from .dynamic_schema import discover_fields, _minimal_fields
from .templates import get_fields_for_topic, resolve_topic
from .field_registry import get_field_type
from . import gliner_extractor
from .gliner_extractor import Extraction as ExtractionEntry

logger = logging.getLogger(__name__)


@dataclass
class ExtractionResult:
    """Structured extraction result."""
    topic: str
    field_source: str  # "manual_registry" | "dynamic_discovery" | "error"
    extracted_data: dict[str, Optional[str]] = field(default_factory=dict)
    sender: dict[str, Optional[str]] = field(default_factory=dict)
    subject: str = ""
    attachments: list = field(default_factory=list)
    field_provenance: dict[str, dict] = field(default_factory=dict)

    def to_dict(self) -> dict:
        return asdict(self)

    def to_json(self, indent: int = 2) -> str:
        return json.dumps(self.to_dict(), indent=indent, ensure_ascii=False)


class TopicEmailExtractor:
    """Generic, zero-cost email extraction engine.

    Accepts an ``.eml`` file path (or raw RFC-822 text) and a topic string.

    **Two-tier field resolution**:
      1. **Manual registry** (``core.templates``) — looks up pre-defined
         field lists for known topics (e.g. ``"job application"``,
         ``"dmarc report"``, ``"invoice"``).  This is the primary path.
      2. **Dynamic discovery** (``core.dynamic_schema``) — derives field
         names from the email body via key-value pairs, noun phrases, and
         semantic similarity.  This is the fallback for unrecognised topics.

    Extraction is performed with a local GLiNER zero-shot model when available;
    otherwise a regex-based fallback is used.  All ML backends are optional
    and lazily loaded.
    """

    def __init__(
        self,
        gliner_threshold: float = gliner_extractor.GLINER_THRESHOLD,
        max_dynamic_fields: int = 20,
    ):
        """Initialise the extractor.

        Args:
            gliner_threshold: Confidence threshold for GLiNER predictions.
            max_dynamic_fields: Cap on the number of fields generated by
                dynamic discovery (prevents runaway extraction).
        """
        self.gliner_threshold = gliner_threshold
        self.max_dynamic_fields = max_dynamic_fields

    def extract(
        self,
        eml_source: str,
        topic: Optional[str],
        raw_text: Optional[str] = None,
    ) -> ExtractionResult:
        """Extract structured data from an email for a given topic.

        Args:
            eml_source: Path to a ``.eml`` / ``.emlx`` file, or raw RFC-822
                text.  When *raw_text* is provided, *eml_source* is used
                only as a label/filename in the output.
            topic: The extraction topic (e.g. ``"job application"``,
                ``"vendor inspection"``).  ``None`` or empty strings are
                treated as an unmapped topic, triggering dynamic discovery
                with universal common fields.  Known topic aliases (e.g.
                ``"career application"`` for ``"job application"``) are
                resolved to their canonical form.
            raw_text: Optional raw email text.  When provided, takes
                precedence over reading *eml_source* as a file.

        Returns:
            An :class:`ExtractionResult` with ``topic``, ``field_source``,
            ``extracted_data``, ``sender``, ``subject``, ``attachments``,
            and ``field_provenance`` (per-field confidence + method).
        """
        # 1. Parse the email.
        # raw_text (if provided) always wins; otherwise eml_source is treated as
        # a file path.  When neither is provided (None / empty), proceed with
        # an empty ParsedEmail so the engine never crashes on missing input.
        if raw_text is not None:
            from .eml_parser import parse_raw_email
            email = parse_raw_email(raw_text)
        elif eml_source:
            email = parse_eml(eml_source)
        else:
            from .eml_parser import ParsedEmail
            email = ParsedEmail(body="")

        # 2. Discover fields for the topic (manual registry → dynamic fallback).
        canonical_topic, field_names, field_source = self._discover_fields(topic, email)

        # 3. Extract values for each field (returns Extraction provenance objects).
        body = self._get_body_text(email)
        extraction_results = self._extract_fields(field_names, body)

        # Split into bare values (backward-compatible extracted_data) and
        # full provenance dicts for transparency, matching LLM-level output.
        extracted_data: dict[str, Optional[str]] = {}
        field_provenance: dict[str, dict] = {}
        for fn in field_names:
            ext = extraction_results.get(fn)
            if ext is not None:
                extracted_data[fn] = ext.value
                field_provenance[fn] = ext.to_dict()
            else:
                extracted_data[fn] = None
                field_provenance[fn] = ExtractionEntry(
                    value=None, confidence=0.0, method="none", raw=None
                ).to_dict()

        # 4. Extract sender info.
        # When the email is forwarded, the real sender is the *forwarded*
        # sender (the person who originally wrote the message), not the
        # forwarder in the From: header.
        sender = extract_sender(email.from_header)
        fwd_sender: dict[str, Optional[str]] = {"name": None, "email": None}
        is_forwarded = detect_forwarded(email.subject, email.body)
        if is_forwarded:
            fwd_sender = extract_forwarded_sender(email.body)
            if fwd_sender.get("name") or fwd_sender.get("email"):
                sender = fwd_sender

        # Sender fallback: when body extraction fails for name/email-type fields,
        # fall back to the parsed sender contact info from the From header.
        # Uses semantic field-type detection so it works for ANY field name
        # that refers to a person name or email (candidate_name, personal_name,
        # full_name, email_address, sender_email, etc.) — not just hardcoded
        # template fields.  This is LLM-like: extracting contact info from
        # message headers as a fallback when the body lacks it.
        sender_name = sender.get("name")
        sender_email = sender.get("email")
        for fn in field_names:
            if extracted_data.get(fn):
                continue  # Already has a value from body extraction
            ft = get_field_type(fn)
            if ft == "person" and sender_name:
                extracted_data[fn] = sender_name
                field_provenance[fn] = ExtractionEntry(
                    value=sender_name, confidence=0.90,
                    method="sender_fallback", raw=email.from_header,
                ).to_dict()
            elif ft == "email" and sender_email:
                extracted_data[fn] = sender_email
                field_provenance[fn] = ExtractionEntry(
                    value=sender_email, confidence=0.95,
                    method="sender_fallback", raw=email.from_header,
                ).to_dict()

        return ExtractionResult(
            topic=canonical_topic,
            field_source=field_source,
            extracted_data=extracted_data,
            sender=sender,
            subject=email.subject,
            attachments=[a.__dict__ if hasattr(a, "__dict__") else a
                         for a in getattr(email, "attachments", [])
                         if hasattr(a, "__dict__")],
            field_provenance=field_provenance,
        )

    def _discover_fields(
        self, topic: Optional[str], email: ParsedEmail
    ) -> tuple[str, list[str], str]:
        """Resolve topic → canonical topic, field names, and field source.

        Dual-path resolution — both paths are ALWAYS evaluated and their
        field lists are merged, so no content is ever discarded just because
        one path fails:

          1. Manual registry (``core.templates``) — pre-defined field lists
             for known topics.
          2. Dynamic discovery — derives fields from the email body as a
             complementary path even for recognised topics.

        Returns:
            (canonical_topic, field_names, field_source)
        """
        topic = (topic or "").strip()
        body = self._get_body_text(email)

        # ── Path A: Manual field registry ────────────────────────────────
        registry_fields = get_fields_for_topic(topic)
        canonical = resolve_topic(topic) or topic if registry_fields else topic
        used_registry = registry_fields is not None

        # ── Path B: Dynamic discovery ────────────────────────────────────
        dynamic_fields = discover_fields(topic, body)
        if len(dynamic_fields) > self.max_dynamic_fields:
            dynamic_fields = dynamic_fields[: self.max_dynamic_fields]
        if not dynamic_fields:
            dynamic_fields = _minimal_fields()

        # ── Merge both paths, deduplicated, preserving order ─────────────
        seen: set[str] = set()
        merged: list[str] = []
        all_fields = (registry_fields if used_registry else []) + list(dynamic_fields)
        for fn in all_fields:
            if fn not in seen:
                seen.add(fn)
                merged.append(fn)

        field_source = "manual_registry" if used_registry else "dynamic_discovery"
        return (canonical, merged, field_source)

    def _get_body_text(self, email: ParsedEmail) -> str:
        """Get the body text for extraction.

        Plain text is preferred; HTML is converted to text when no plain
        body exists.  Forwarded-message envelopes (``From/Date/Subject/To``
        blocks injected by mail clients) and quoted-reply markers
        (``----- Original Message -----``, ``On ... wrote:``) are stripped
        so that only the actual message content is analysed.
        """
        if email.body:
            body = email.body
        elif email.html_body:
            from .eml_parser import html_to_text
            body = html_to_text(email.html_body)
        else:
            body = ""
        body = body.replace("\r\n", "\n").replace("\r", "\n")
        body = strip_forward_envelope(body)
        body = strip_quoted_reply(body)
        body = strip_trailing_signature(body)
        return body

    def _extract_fields(
        self, field_names: list[str], body: str
    ) -> dict[str, ExtractionEntry]:
        """Extract values for the given fields from the body text.

        Returns a dict mapping each field name to an
        :class:`ExtractionEntry` (value, confidence, method, raw).
        When the same logical concept appears under different names
        (e.g. ``candidate_name`` from the registry and ``personal_name``
        from dynamic discovery) both entries are populated independently —
        no later value silently overwrites an earlier one.
        """
        if not field_names or not body:
            return {
                fn: ExtractionEntry(value=None, confidence=0.0,
                                    method="none", raw=None)
                for fn in field_names
            }

        # Use GLiNER (or regex fallback) for extraction.
        return gliner_extractor.extract_with_gliner(
            body, field_names, threshold=self.gliner_threshold
        )

    def extract_batch(
        self,
        eml_sources: list[str],
        topic: str,
        raw_texts: Optional[list[str]] = None,
    ) -> list[ExtractionResult]:
        """Extract from multiple emails, one per item.

        Includes per-item try/except so one bad input doesn't abort the batch.
        """
        results: list[ExtractionResult] = []
        for i, source in enumerate(eml_sources):
            raw = raw_texts[i] if raw_texts and i < len(raw_texts) else None
            try:
                result = self.extract(eml_source=source, topic=topic, raw_text=raw)
                results.append(result)
            except Exception as exc:  # noqa: BLE001
                logger.warning("Batch item %d failed: %s", i, exc)
                results.append(ExtractionResult(
                    topic=topic,
                    field_source="error",
                    extracted_data={"error": str(exc)},
                ))
        return results

    def __call__(
        self,
        eml_source: str,
        topic: Optional[str],
        raw_text: Optional[str] = None,
    ) -> dict:
        """Convenience: same as :meth:`extract` but returns a plain dict."""
        return self.extract(eml_source, topic, raw_text).to_dict()


# ── Module-level convenience functions ─────────────────────────────────────────

def extract(
    eml_source: str,
    topic: Optional[str],
    raw_text: Optional[str] = None,
) -> dict:
    """Extract structured data from an email (module-level convenience).

    Equivalent to::

        TopicEmailExtractor().extract(eml_source, topic)
    """
    return TopicEmailExtractor().extract(eml_source, topic, raw_text).to_dict()
